---
- name: Converge
  hosts: molecule
  gather_facts: false
  become: true

  pre_tasks:
    - name: Create Auth File
      ansible.builtin.file:
        path: /var/log/auth.log
        state: touch
        mode: 0644

  roles:
    - role: ansible-role-fail2ban
